spring:
  application:
    name: movie-service
  profiles:
    active: dev
  boot:
    admin:
      client:
        url: http://localhost:9020
        instance:
          name: Movie API Service
server:
  servlet:
    context-path: /store/api/v1
  port: 9200
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
